### ISSUE TITLE
How to change direction of slider

### ISSUE THREAD

**Issue by kooroshekabir** [webbiesdk/SudoSlider#22]
Hi.When I changed direction of style.css to RTL slides were fade

**Comment by webbiesdk** [comment]
What?

I have no idea what you mean, you need to send a link or something.

**Comment by kooroshekabir** [comment]
i have a index.html,style.css and your slide show files.when i use "*{direction:rtl}" in style.css thire texts that in <li> were fade

**Comment by kooroshekabir** [comment]
download this file https://www.mediafire.com/?uha4s3bo9z1co5b I changed your demo version like my project.I add *{direction:rtl;} in first line of style.css

**Comment by webbiesdk** [comment]
I see now, SudoSlider assumes that the text-direction i left-to-right when calculating where the slides are supposed to be. 
Making it support right-to-left is not going to happen. 

But you can fix it by adding the following CSS. 

    #slider, #slider > * {
        direction: ltr !important;
    }
