### ISSUE TITLE
link from another page

### ISSUE THREAD

**Issue by tingfast** [webbiesdk/SudoSlider#24]
How can I link to a specific slide from external page?
I want to link to ("javascript:void(0);" class="customLink" data-target="2")
using( href="ArtistMall.shtml").
Thank you!
Ting

**Comment by webbiesdk** [comment]
You have to use the history option. 

You can see an example here: 
http://webbies.dk/assets/files/SudoSlider/package/demos/history.html#third-slide

Notice that the link above links to the third slide in the slider, which has been given the name "third-slide" using numericText.
