### ISSUE TITLE
start random

### ISSUE THREAD

**Issue by tingfast** [webbiesdk/SudoSlider#25]
Is there a way to make the slider to start at a random image?
thank you!
Ting

**Comment by webbiesdk** [comment]
If you look in the random.html, as it was a couple of minutes ago, you could see that it was actually quite easy to make this yourself. 

But you are not the first to ask, so i implemented it as an explicit feature in the slider 1fc3de8465d74a7a61d150a3cecdec21011df828. 

Download the newest version here from github ( https://github.com/webbiesdk/SudoSlider/archive/master.zip ), and set startSlide:"random"
