### ISSUE TITLE
restart the slider

### ISSUE THREAD

**Issue by tingfast** [webbiesdk/SudoSlider#28]
I am sorry for bothering you again but  I have build a vertikal slider with image links, when click on the link it does not start again, I have to reload the page.
thanks!

**Comment by webbiesdk** [comment]
I'm not sure i completely understand the issue. 

Could you send a link to a page that has the issue, that would make things easier.

**Comment by tingfast** [comment]
here is the link:

 konstruntsiljan.se

Ting

Frank Lindbeck
tfn: 070-395 60 59

2015-03-21 12:23 GMT+01:00 webbiesdk <notifications@github.com>:

**Comment by webbiesdk** [comment]
Hmmm. I think what happens is that the slider registers that you move it when you click on a link. 
This can stop the slider. 

Try to add the following option. 

    resumePause: 2000

That way the auto-animation should never stop. 

If it still happens, it is something with the code that stops auto on mouseover.

**Comment by tingfast** [comment]
It works fime now, gonna press the donate button!
Ting
