### ISSUE TITLE
Order of images

### ISSUE THREAD

**Issue by potsu** [webbiesdk/SudoSlider#29]
Is there a way to set an order to the images that I have in the slide show.  Either by name, or by a field in the content part of the drupal site. Thanks http://www.redlodgemountain.com/

**Comment by webbiesdk** [comment]
You can just change the order of the elements in the HTML code. 

You can also use something like this if you want to change the order with some JavaScript: 
http://stackoverflow.com/questions/7628627/change-order-divs-with-jquery

The JavaScript needs to run before the slider is initialized.

**Comment by potsu** [comment]
Thanks Webbie Sdk

Any hints on where I might find that html code in the rather large drupal backend?

Thanks

Paul Otsu
[signature]
Find Montana Skiing, Pure and Simple on:
Facebook<https://www.facebook.com/redlodgemountain>, Instagram<http://instagram.com/redlodgemountain>, Youtube<http://www.youtube.com/redlodgemountain>, Twitter<https://twitter.com/redlodgemntn>, and online at RedLodgeMountain.com<http://www.redlodgemountain.com/>

**Comment by webbiesdk** [comment]
Nope, never used Drupal
