### ISSUE TITLE
History effect is gone

### ISSUE THREAD

**Issue by iXshad0w** [webbiesdk/SudoSlider#30]
Hi there, 
used sudo slider because its very nice.
i wanted to enable history so i did... (duh), but when i navigate through pages the effects are gone. weird thing is when i go back (with the history) the page slides smoothly.

TL;DR

forward animation broken when history is enabled,
backward animation still works when history is enabled

this is the config i use

$("#slider").sudoSlider({ 
        ajax: [
           'pages/home.php', 
           'pages/beheer.php', 
           'pages/consultancy.php', 
           'pages/datacenter.php', 
           'pages/netwerkOntwerp.php',
           'pages/voip.php'
        ],
        effect:"slide",
        history:true,
        customLink:'.link',
        prevNext: false,
        speed:500,
        interruptible:true,
        responsive:false,
        numericText:['Home', 'Beheer', 'Consultancy', 'Datacenter', 'NetwerkOntwerp', 'Voip']
});

**Comment by webbiesdk** [comment]
Congratulations, you actually found a bug. 

For now you can fix it by setting interruptible to false, but I'll look into fixing the actual bug.

**Comment by iXshad0w** [comment]
that fixed the issue thanks. if this bug is resolved i would like to hear so. it will be much nicer if interruptions are possible.

**Comment by webbiesdk** [comment]
Should be fixed in the commit i just pushed. 

Just download the latest version here from github https://github.com/webbiesdk/SudoSlider/archive/master.zip to get the fixed version.

**Comment by iXshad0w** [comment]
hooray thanx for the great support and fast fix

**Comment by webbiesdk** [comment]
You're welcome.
