### ISSUE TITLE
Fix navigation

### ISSUE THREAD

**Issue by Valeka** [webbiesdk/SudoSlider#32]
Hi there! Thanks for great slider. I'm using this version for my site 
http://webbies.dk/assets/files/SudoSlider/package/demos/thumbnails%202.html

Now I wonder, is there any way to make navigation fixed so when you click on one thumbnail not to scroll on left or right whole navigation. I want to move navigation only by arrows.

Thanks!

**Comment by webbiesdk** [comment]
Just remove the line 

    controlsSlider.goToSlide(targetSlide);

**Comment by Valeka** [comment]
Thanks! Perfect!
