### ISSUE TITLE
Function adjust declared twice

### ISSUE THREAD

**Issue by fbasso** [webbiesdk/SudoSlider#33]
Hi,

I tried to update sudoSlider in my project form version 3.3.2  to 3.4.1, and I faced a strange issue on IE8 : only the first image is displayed with all the thumbnails, but the slider is stopped (the image doesn't change), even if I click on a thumbnail.

It's strange because I can't reproduce it on your demo page : http://webbies.dk/assets/files/SudoSlider/package/demos/thumbnails.html

Investigating my own use case, I found out that the issue comes from commit d25fcb1 :

The line `baseSlider.adjust = function adjust(repeat) {` overrides the function adjust defined before by `function adjust(clicked)` (in my case and on IE8 only, I can't explain why yet).

I just removed the second definition by : `baseSlider.adjust = function (repeat) {`, and it works.

Could you please see if you can fix it, if it doesn't cause any regression ? Without this fix, I can't upgrade as I need support for IE8.

Thanks.

**Comment by webbiesdk** [comment]
No problem with renaming it. 

An interresting thing however, is that the minified code didn't change one bit, so you should be able to use that already.

**Comment by fbasso** [comment]
Interesting and true indeed, the minified code doesn't have the issue (I use the unminified code in dev mode and process the minification in production mode).

Thanks for the quick change!

**Comment by webbiesdk** [comment]
You're welcome. 

I use always use the minified code, unless i want to use a debugger, so i didn't catch this error.
