### ISSUE TITLE
How to Setup

### ISSUE THREAD

**Issue by giukra96** [webbiesdk/SudoSlider#35]
The "How to Setup" Part of your website won't be shown when clicking on it. The slider always slides to the next slide or to the previous but always skips the actual "how to setup" - slide that should be shown.
This only appers when the slider already slided once and you want to go back to "how to setup".
http://webbies.dk/SudoSlider/help/#Howto

**Comment by webbiesdk** [comment]
Thanks. 

On that particular page i had previously put in a fix for a "bug" in SudoSlider, then later changed SudoSlider, which made that fix do about the oposite of what it was supposed to do. 

So removing my previous fix fixed it. 

Thanks for telling me. 

If it isn't fixed when you go access the page, try to do a hard refresh.
