### ISSUE TITLE
Slider flickering last image before load, image links breaking randomly

### ISSUE THREAD

**Issue by makl2015** [webbiesdk/SudoSlider#36]
We are using the Sudo Slider and have encountered a couple of issues.  When the home page of our site loads, the sudo slider flashes the last image in the sequence before starting at the first image.  Have you encountered this before?  We have updated to the latest version, but still have no improvement.  More importantly, the slider image links are breaking, making the images that should be in the slider disappear.  
We are using JSON to load image versions (small, med, large) into the slider for different screen sizes.  Any help that you can provide would be greatly appreciated!  Thank You!

**Comment by webbiesdk** [comment]
Lets take one issue at a time. 

1) The flashing images on initialize. Yes that sound somewhat familiar. A fix could be set the opacity of all the images (except the first) to 0.001, and then change it back once the slider has initialized (see the option initcallback). 
That might fix it (not sure), but to be more precise, i need more information. 
Do you use the sliders Ajax functioality? 
What does you slider div look like, does it contain nothing, some divs or an ul tag with li tags under? 

2) Breaking slider image links. 
No idea. 
I need to see what you are talking about (can you create an example on JSFiddle, or send a link).
