### ISSUE TITLE
TAB key on input text between slides

### ISSUE THREAD

**Issue by molocLab** [webbiesdk/SudoSlider#37]
When 2 slides have got one or more input text and you click the TAB key on the last input text of the first slide (focused), the focus passes to the first input of the second one and the slider breaks out.

**Comment by webbiesdk** [comment]
You might be able to use something like this: http://stackoverflow.com/questions/1561021/prevent-tabstop-on-a-element-anchor-link-in-html

With that you should be able to stop all tabbing between input fields. 

You can properly do something where all the inputs on non-active slides get tabindex=-1 with some JavaScript. (That i can do, but wont do for free).
