### ISSUE TITLE
Slider image issue

### ISSUE THREAD

**Issue by Fatih07** [webbiesdk/SudoSlider#38]
Hello,
i'm having problem with slider images. I just updated sudoslider to latest version but nothing happened.

Problem is when you load any page like http://www.discerningcollection.com/countries/morocco/ Slider images comes but not in slider class.

But if i refresh the page, it works fine.
I was using cloudflare and paused but nothing changed again.
Can you help please? I'm trying to sort out before 2 days!
![slider](https://cloud.githubusercontent.com/assets/12713753/7936275/7b84a700-0940-11e5-89de-11bde9bda4a7.png)
![slider2](https://cloud.githubusercontent.com/assets/12713753/7936277/7ba4ac6c-0940-11e5-812c-05e36a25f0af.png)

**Comment by webbiesdk** [comment]
When i try to load the page, the images does look like your top image, until the slider initializes and moves everything where it should be. 

And for me it loads every time. 

What browser are you using, and have you tried clearing the browser and dns cache (in case of Chrome, also Chromes dns cache)?

Also, it is difficult to read what you mean from the question. 
You say if you refresh the page it works fine. So anytime you come in from another page it doesn't work.

**Comment by Fatih07** [comment]
Thank you for your quick response! You are very kind.
Well i just tested again with iexplore v.10 Same problem. Mostly i'm having problem with ie browsers.
Here is screenshot from ie9
![iexplore9](https://cloud.githubusercontent.com/assets/12713753/7937363/3bca8302-0948-11e5-9873-9434e3143e34.png)


If you take a look top image that is the problem i'm having. images load fine but slider not initialize.

Can you check these pages for example please?
http://www.discerningcollection.com/destinations/kumlubuk-and-the-bozburun-peninsula/
http://www.discerningcollection.com/destinations/lemnos/

I just tested another computer who never visited that website before, same problem with ie. 11
Here is screenshot from ie11
http://prntscr.com/7c928r

**Comment by webbiesdk** [comment]
I also just tried on another computer, and i still can't replicate it. 

Try (using the newest IE available) to open up the console (press F12). 

And look at what is printed when the slider fails to start, and compare that to how it looks when the slider does start.

**Comment by Fatih07** [comment]
Well i just removed some unusual js includes and it works fine for me too.
I will ask some clients.

Thank you for your quick and very helpfull response!
