### ISSUE TITLE
fadein in combination with captions

### ISSUE THREAD

**Issue by dorpm** [webbiesdk/SudoSlider#39]
Hi,

I try to combine fadein with keyboard and captions but the fadein doesn't work. Could you help me with this?

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Sudo Slider | Captions demo</title>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />    

    <link rel="STYLESHEET" type="text/css" href="../css/style.css">

	<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="../js/jquery.sudoSlider.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){	
			var loadFadeSpeed = 400;
			var ajaximages = [
			    '../images/01.jpg', 
			    '../images/02.jpg', 
			    '../images/03.jpg', 
			    '../images/04.jpg', 
			    '../images/05.jpg'
			];
			var imagestext = [
			          'Text1',
                'Text2',
                'Text3',
                'Text4',
                'Text5'
			];
			var sudoSlider = $("#slider").sudoSlider({
                effect: "fade",
                responsive: false,
                preloadAjax: false,
			          ajax: ajaximages,
			    
                ajaxLoad: function(t){
			        $(this)
			            .css("position","relative")
			            .append('<div class="caption" >' + imagestext[t-1] + '</div>');
			    },
			    
			    beforeAnimation: function(t){
			        $(this).children('.caption').hide();
			    },
			    afterAnimation: function(t){
			        $(this).children('.caption').slideDown(400);
			    },
			    
			      loadStart: function () {
                // In loadStart and loadFinish "this" refers to the SudoSlider object. (Here same as "sudoSlider").
                var slides = this.getSlide(this.getValue("currentSlide"));
                slides.animate(
                        {opacity: 0.5},
                        {
                            queue: false,
                            duration: loadFadeSpeed
                        }
                );
            },
            loadFinish: function () {
                var slides = this.getSlide(this.getValue("currentSlide"));
                slides.animate(
                        {opacity: 1},
                        {
                            queue: false,
                            duration: loadFadeSpeed
                        }
                );
            },
            initcallback: function () {
                var container = $(".slideContainer");
                // A little hack to get the actual height of the slider.
                var height = container.height("auto").height();
                container.height(0);

                // Fadein and SlideIn.
                container.animate({opacity: 1, height: height}, 800, function () {
                    container.height("auto");
                });
			     }
			    
			});

			$(document).keydown(function (e) {
			    if (e.which == 39) { // Arrow right
			        sudoSlider.goToSlide("next");
			    }
			    else if (e.which == 37) { // Arrow left. 
			        sudoSlider.goToSlide("prev");
			    }
			});
			
		});
	</script>
	<style>
	.caption {
	    position:absolute;
	    bottom:0;
	    left:0;
	    width:100%;
	    text-align:center;
	    color:black;
	    background:white;
	    background:transparent;
	    background:rgba(255,255,255,0.7);
	    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#a3ffffff,endColorstr=#a3ffffff);
	    zoom: 1;
	}
	</style>
</head>

<body>
<div id="container">
	<h1>HEADING 1</h1>
		<div id="slider" style="width: 1024px;"></div>
</div>

</body>
</html>

**Comment by webbiesdk** [comment]
What do you mean that the fadein doesn't work? 

When I tried to copy-paste your code, the fade effect worked fine on the slider.

If its on the captions that are the problem, then you are on your own. 

Closed until more info is available.
