### ISSUE TITLE
Soundy Music Plugin

### ISSUE THREAD

**Issue by quickpics** [webbiesdk/SudoSlider#40]
Using word press with Sudo Slideshow I cant get my plugin for Sound to work. I use soundy plugin

**Comment by webbiesdk** [comment]
It is Soundy plugin that doesn't work, and you expect help here? 

Besides, I would need a link to a page with the problem, before i would even consider looking into the issue.

**Comment by quickpics** [comment]
My bad but thanks for the sarcasm. It would have been nice to have someone
that was going to act professional.  I use SUDO for my slideshow and before
I started using SUDO the soundy plugin worked just fine. I thought you
might be aware of issues using the soundy plugin with your program. I guess
i was worng and I certainly wouldnt expect you to look into it since its
not your problem. I will contact soundy and I will be sure to not recommend
using your program with any of my collegues.

Your are not into customer service obviously and I terribly disappointed

*Brent R. Eckley*

*QUICK PICS*

REAL ESTATE PHOTOGRAPHY

*Pho**ne        888-244-8710*

*Fax             877-421-9897*

*Cell             254-498-5037*
