### ISSUE TITLE
Changing Numeric Controls to different setup

### ISSUE THREAD

**Issue by kylebellamy** [webbiesdk/SudoSlider#43]
My client loves the slider styling but wanted to see if it were possible to make the numerics be 1 / 15 rather than the whole list. I realize this may be well outside the scope of the script but wanted to see if you had any guidance on this alternate labeling. We would use the prev and next to navigate.

**Comment by webbiesdk** [comment]
You mean that there is just the text "1/15", where 1 is the current slide and 15 is the total number of slides. 
In that case, you might find some help here: http://webbies.dk/assets/files/SudoSlider/package/demos/basic%20callbacks.html

**Comment by kylebellamy** [comment]
Ah! Still learning the finer details of scripting. Wasn't sure that they were what I needed. Thanks again for you patient direction.
