### ISSUE TITLE
Rows

### ISSUE THREAD

**Issue by dbluco** [webbiesdk/SudoSlider#44]
Right now I have a slider with a slide count of 5. What I'd like to do is have two rows of five. I tried just making two sliders but they are out of sync. How do I accomplish this?

**Comment by webbiesdk** [comment]
To make the two sliders in sync, you have to make sure that whenever one slides animates, then the other one follows. This can be done using the callback options provided by SudoSlider. 

You can see how to do it here: http://jsfiddle.net/32m7bhtn/2/

If you need more than two sliders in sync, then beforeCall would need an array of sliders of some sort.
