### ISSUE TITLE
nested slider with vertical thumbnails

### ISSUE THREAD

**Issue by BobSyl** [webbiesdk/SudoSlider#45]
Hi there

Given that the pictures i want to showcase are all in portrait, I would like to customise your nested slider demo as such: I want to display vertical thumbnails for each of the 3 to 4 children in a nested slide.
I can manage fine with html but javascript is beyond my knowledge and I don't know how to begin customising your slider.

Please assist

**Comment by webbiesdk** [comment]
This is not an issue, this is you hoping i will do your job for free.
