### ISSUE TITLE
How can I link to a certain slide through another page 

### ISSUE THREAD

**Issue by VukadinNedeljkovic** [webbiesdk/SudoSlider#47]
Hello, I am using your slider for a portfolio. I want to link form another page to a certain slide . How can I do that? Slider is great btw, thank you.

**Comment by webbiesdk** [comment]
Look at the history feature, its in the docs, and there is an example here: http://webbies.dk/assets/files/SudoSlider/package/demos/history.html#third-slide

(Notice that the link is to the third slide)
