### ISSUE TITLE
How do I embed html without having to create an html page?

### ISSUE THREAD

**Issue by johngoad1** [webbiesdk/SudoSlider#48]
I want to be able to pull content from a data source and then pass it as html:

ajaxSlides = [
'<p><img src="../images/Image1.jpg" /> This is just some text 1!</p>",
'<p><img src="../images/Image2.jpg" /> This is just some text 2!</p>",
'<p><img src="../images/Image3.jpg" /> This is just some text 3!</p>",
'<p><img src="../images/Image4.jpg" /> This is just some text 4!</p>"
];

var sudoSlider = $(mainSlider).sudoSlider({
                ajax: ajaxSlides ,
                numeric: true
            });

When I do this, it always creates an image tag and sets the src equal to my html!

**Comment by johngoad1** [comment]
Sorry, my html got encoded:

I want to be able to pull content from a data source and then pass it as html:

AjaxSlides = [
&#39;&lt;p&gt;&lt;img src=&quot;../images/image1.jpg&quot; /&gt; Just some text 1!&lt;/p&gt;&#39;,
&#39;&lt;p&gt;&lt;img src=&quot;../images/image2.jpg&quot; /&gt; Just some text 2!&lt;/p&gt;&#39;,
&#39;&lt;p&gt;&lt;img src=&quot;../images/image3.jpg&quot; /&gt; Just some text 3!&lt;/p&gt;&#39;,
&#39;&lt;p&gt;&lt;img src=&quot;../images/image4.jpg&quot; /&gt; Just some text 4!&lt;/p&gt;&#39;,
&#39;&lt;p&gt;&lt;img src=&quot;../images/image5.jpg&quot; /&gt; Just some text 5!&lt;/p&gt;&#39;,
];

var sudoSlider = $(mainSlider).sudoSlider({
 ajax: ajaxSlides ,
 numeric: true
 });

When I do this, it always creates an image tag and sets the src equal to my html!

**Comment by webbiesdk** [comment]
AjaxSlides takes URL's of stuff that SudoSlider should load. 
What you should do instead is make some other JavaScript to put your html into the slider, before initializing SudoSlider.
