### ISSUE TITLE
Text slide

### ISSUE THREAD

**Issue by GThib** [webbiesdk/SudoSlider#49]
Can I use a piece of paragraph text in Sudo Slider in the way that the text will to be resizing (same character size, ex. 12px) on account of display size but will be gradually fitting in the slider box?

I am quite newbie and have to prepare my presentation page.
I would be thankful for hammer-way guidance on presenting several pages of paragraph text using SudoSlider. Shall I create a new wordpress page and put all the bunch-of-letter codes into?
How can I add a page(s) of text to the slider as slides?

I would be seriously grateful for any help on above. Thank you in advance.

Does anyone visit this page ever?

**Comment by webbiesdk** [comment]
Someone does visit this page every once in a while. (Although not often). 

You can put whatever content you want inside each slide, like done in the rich content demo: http://webbies.dk/assets/files/SudoSlider/package/demos/rich%20content.html (look at the source code). 

And I'm not familiar with WordPress, so I don't think i can help you more.
