### ISSUE TITLE
Does it support  vertical mutiple sliders?

### ISSUE THREAD

**Issue by Kennersky** [webbiesdk/SudoSlider#52]
How could I change something that can support mutiple sliders changing by vertical direction?
Like the picture bellow:
![1](https://cloud.githubusercontent.com/assets/2129521/14872506/9067b200-0d1f-11e6-8b97-6cd2615cacf5.jpg)

**Comment by webbiesdk** [comment]
Something like this? http://webbies.dk/assets/files/SudoSlider/package/demos/vertical%20fade.html

You can change `effect: "fade"` to `effect: "slide"` if you want a traditional slide-animation.
