### ISSUE TITLE
Firefox responsive bug

### ISSUE THREAD

**Issue by sasovin** [webbiesdk/SudoSlider#55]
Hi!
Sometimes, such as when the window width 991px in Firefox observed to twitch 1 px image, after turning slide.
http://webbies.dk/assets/files/SudoSlider/package/demos/responsive%20maxwidth.html
The error due to the fact that when responsive = true, then the width of the slide has a fractional value. No rounding.
http://joxi.ru/MAj17VxHvJ06B2
Thanks! Good slider!!!

**Comment by webbiesdk** [comment]
It is something I've had issues with before, I'll take a look at it again, and see if i can get rid of it.

**Comment by webbiesdk** [comment]
Ok, i made sure the individual slides have a whole number width now. Doesn't seem to affect the animations.

**Comment by sasovin** [comment]
Thank you, but now there was another problem. Right peeps 1 pixel of the next slide.
http://joxi.ru/BA0pneKsBxl44A
Perhaps in such cases needs to be done, for example, the width of the first slide as:
width_first_slide=Round(width_slide)+(width_window-Round(width_slide)*count_slide)
or similar.
