### ISSUE TITLE
Bug with continuous option

### ISSUE THREAD

**Issue by devlat** [webbiesdk/SudoSlider#58]
I use JQuery's sudoSlider plugin. But if dataset contain more than 5 elements and "continuos" option is true, sudoSlider is not working properly. When I press nextHtml button - sudoSlider scrolling more than one elements(So if you click on the next button you will be redirected to the second slide of the list of image which would completly jump the first real slide of the list), but it should be only one element. Below is sudoSlider initialize code:

$(".accessories-list-wrapper").sudoSlider({
    slideCount: 4,
    continuous: true,
    nextHtml: '<span class="fa-angle-right"></span>',
    prevHtml: '<span class="fa-angle-left"></span>'
});

sudoSlider version is 3.4.7.

P.S. Updated plugin to 3.4.10, but have same bug
So, I found this comment at http://webbies.dk/SudoSlider/help/ask-me/?quip_start=60&quip_limit=30:

There is a bug with the continuous slider :

By default, the first slide to appear should be the first of the list of image. With the continious slider its the last slide which appear first.

So if you click on the next button you will be redirected to the second slide of the list of image which would completly jump the first real slide of the list.

If you click on previous, the current slide wont change since we are already looking at the last slide. You have to click a second time to go the previous slide.

The bug would be fix if the first slide to appear would be the first slide of the list of image instead of the last.

Hope you can understand what i'm trying to said ;)

**Comment by devlat** [comment]
Hmm, in another widget with sudoSlider all works correctly.

**Comment by devlat** [comment]
I set slideCount option to amount of data elements and now all works correctly.

**Comment by webbiesdk** [comment]
If you could, it would be nice to have a complete example of a page that demonstrates the bug. 

But otherwise, it seems that you fixed the issue yourself, so I'm closing the issue.
