### ISSUE TITLE
WordPress jQuery not compatible

### ISSUE THREAD

**Issue by toleabivol** [webbiesdk/SudoSlider#59]
Hello,

when used in WP latest version 3.4.10 throws error : `Uncaught TypeError: $ is not a function`
Then I found this commit that is not included in released code:
https://github.com/webbiesdk/SudoSlider/commit/33253a1ea51af256021ba81ddb4c4831369c1552

**Comment by webbiesdk** [comment]
So you are suggesting I create a new release that includes the mentioned commit?

**Comment by toleabivol** [comment]
When I use that commit's code , everything works for me.
So yes , I would suggest you to include it in release so other WP users don't get this error.
