### ISSUE TITLE
Slider disappearing on refresh

### ISSUE THREAD

**Issue by jlinners** [webbiesdk/SudoSlider#61]
Hi there,

I have used SudoSlider a few times before and it has worked great but am having a strange issue in Google Chrome this time. I have implemented exactly how I have previously.

Please see link here - http://jackjackjack.co.uk/test/

I am using it with enquire.js (http://wicky.nillia.ms/enquire.js/) and media-match (https://github.com/weblinc/media-match). Again, I have used this previously and has worked fine.

If you scroll down to 'Team', then resize the window until it snaps to 3 people, then refresh the page, the slider disappears. This doesn't happen every time you refresh but most of the time.

The same happens if you scroll down to 'News' and resize the window until it shows 1 news listing.

Any ideas?

Thanks, Jack

**Comment by jlinners** [comment]
Any ideas?

I'm not sure whether you've stopped support for this or not?

Thanks, Jack

**Comment by webbiesdk** [comment]
I haven't completely stopped support, I just rarely look at it. 

I think I will look at it later, but I tend to have other things to do.

**Comment by jlinners** [comment]
That's fine, thank you for getting back to me.

**Comment by jlinners** [comment]
Happy to donate if you do know what the issue could be.

**Comment by webbiesdk** [comment]
Okay i finally had some time to look into the issue. 
And I couldn't replicate it, the  

I recorded me trying, if I'm doing something wrong.
https://www.youtube.com/watch?v=CIZSTBLhYzk&feature=youtu.be

**Comment by jlinners** [comment]
That video has been blocked due to music playing in the background.

I have attached my video of the issue.

[sudoslider_issue.mov.zip](https://github.com/webbiesdk/SudoSlider/files/1355362/sudoslider_issue.mov.zip)

**Comment by jlinners** [comment]
Is there such a thing that it can't handle there being too much content in one slide?

**Comment by jacklinwood** [comment]
Any ideas?

**Comment by jlinners** [comment]
Any ideas?

**Comment by webbiesdk** [comment]
I still can't replicate it here, so I cannot fix it for good. But I got an idea that might fix it for you. 

For each of the sliders you initialize, like: 
````
var getInTouchCtasCarousel = $("#getintouch_ctas_carousel").sudoSlider({
...
});
````

Add the following below the initialization: 
````
$( window ).load(function() {
    getInTouchCtasCarousel.adjust();
});
````

(The variable name's should match). 

That should hopefully make the slider readjust, once every element on the page has been loaded.

I have no idea if it works, since I'm still unable to replicate it here, but I think it will work.

**Comment by webbiesdk** [comment]
Alternatively, add the following option to all the sliders: 

````
initCallback: function  () {
	var that = this;
	this.adjust();
	$(window).load(function() {
		console.log("bar");
		that.adjust();
	});
}
````
