### ISSUE TITLE
iOS - Transitions are not smooth with jQuery 3.5

### ISSUE THREAD

**Issue by BernardB84** [webbiesdk/SudoSlider#70]
Hello, I use SudoSlider with jQuery 3.5 and transitions on iOS are not smooth.

On this link you can see the problem :
http://dr-rauzy.preprod.ussoft.fr

If I use jQuery 1.11 all is OK.

Thanks for your help.

**Comment by erik-krogh** [comment]
What options are you using, the default?

**Comment by BernardB84** [comment]
$("#slider_page").sudoSlider({
        numeric:false,
        responsive:true,
        auto:true,
        prevNext:false,
        controlsShow:false,
        effect:'boxRandomGrowOut',
        animationZIndex:997,
        speed:'2000',
        pause:'5000'
    });

**Comment by erik-krogh** [comment]
Thanks, but I think I'm stuck.  
Nothing in my code changes between those JQuery versions.  

My best bet is that the feature detection I use to detect whether CSS animations are supported somehow breaks ([here](https://github.com/erik-krogh/SudoSlider/blob/master/js/jquery.sudoSlider.js#L2986)).  
And that my code therefore takes the fallback animation approach ([here](https://github.com/erik-krogh/SudoSlider/blob/master/js/jquery.sudoSlider.js#L2655)).   
I don't have an iOS device to test on, so unfortunately I think I'm stuck.  

If my guess is right, then you can "fix" it by deleting [this if-statement](https://github.com/erik-krogh/SudoSlider/blob/master/js/jquery.sudoSlider.js#L2655-L2661).   
But I don't have time to look further into it (and I don't do paid support any more).  

---- 

Alternatively you can try to set the option `performanceMode: 2` (or `performanceMode: 1` if `2` breaks something).  
That has previously fixed iOS performance, and it should work fine with your setup.  
But I still don't see how jQuery versions could impact that.

**Comment by BernardB84** [comment]
Ok, thanks for your answer.
I'll try that, otherwise I'll look for another solution.
